services:
  kali:
    platform: "linux/arm64"      # always ARM64
    build: .
    image: kali-re-tools:arm64
    working_dir: /work
    volumes:
      - ./:/work
    stdin_open: true
    tty: true
    entrypoint: ["/bin/bash"]